### ISSUE TITLE
@Slf4j LOG variable is not recognised by Intellij IDEA 15 

### ISSUE THREAD

**Issue by myndworks** [mplushnikov/lombok-intellij-plugin#154]
Lombok intellij plugin works pretty well, except it does not recognise the LOG variable. (It marks it in red and thinks the variable is undefined.)

But compiles and runs ok.

Not a show stopper rather annoying. A fix would be appreciated.

Thank you for your help.

**Comment by tomaszganski** [comment]
Hi, I am using intellij 15 with @Slf4j and for me everything works fine.  In my case help me **File > Invalidate Caches / Restart > Invalidate and Restart**

**Comment by myndworks** [comment]
Hi, thanks. I did that still has no luck.

Intellij is still complaining about LOG variable. Other lombok annotations
are working fine.

:-(

Kind Regards
Senthil.

**Comment by Janmm14** [comment]
Double check annotation processing and lombok enabled in project settings.

**Comment by AlexejK** [comment]
By default, Lombok generates a variable called `log` (lower-case). If you placed a new variable name in lombok.config, you have to make sure it's in the `src/main/java`. Lombok itself will search higher up in te structure, however IDEA plugin currently has a limitation where it searches only up to `default` package.

Could it be that you are hitting that specific issue?

**Comment by vict0r81** [comment]
After update to 0.9.7.15 with IDEA 15.0.2. I've experienced almost the same issues with with @Slf4j annotations when I do 'make project' by pressing hot key Command(Ctrl) + F9, IDEA cause error:
Error:(79, 9) java: cannot find symbol
  symbol:   variable log
  location: class <classname>
And point on the line, where I have:
log.error("Error ....");

**Comment by jasontrublu** [comment]
After update to 0.9.8.15 (IDEA 15.0.3) I have the same problem now. previously it was working (don't know if I had 0.9.7 or 0.9.6). Now also other annotations seems to fail, but I cannot see a pattern there

**Comment by AlexejK** [comment]
Interesting. Im using `@Slfj4` and a bunch of other annotations and the latest plugin works fine. However, contrary to you, I'm on EAP 16 version.

**Comment by vict0r81** [comment]
Looks like I've found solution: close IDEA project, delete .idea folder and .iml files in each module, reimport project. Now I can Make project w.o. any issue (at least not with `@Slf4j` annotation).
Another solutions like change IDEA versions (checked on 14.1.6, 15.0.2, 15.0.3, 16 EAP), change lombok plugin version, upgrade lombok dependency itself, even upgrade JDK doesn't make any success results for me.
Hope this solution could be useful.

**Comment by mplushnikov** [comment]
I will close this issue now, because it is not reproducible for me. I hope it is something with your local setup...
Feel free to open new issue if problem still exists!

**Comment by radsimu** [comment]
I just experienced the same thing. Only in one file log was not recognised by intellij - build worked fine. ctrl+a, ctrl+c, delete, ctrl+v, profit

**Comment by WesternGun** [comment]
I just encountered the same problem in Intellij IDEA 2018.1. I just delete the log occurrence, make IDEA warns me to "add the lombok.extern.xxx.jar to classpath", and all is fine. Just get a little bit crazy about this.

**Comment by lucasdaniele1** [comment]
I have fixed it installing Lombok plugin

**Comment by lauriall** [comment]
Just upgraded from version 1.18.8 to 1.18.12 and everything started working ...

**Comment by StefanSchade** [comment]
Just for the record: I just ran into the same problem with IntelliJ Ultimate 2019-3. Stragely enogh this applies only to one module in a multi-maven-project and could not be fixed adjusting the lombok plugin settings. As it is rather an invonvenience, I think, I will ignore it for the moment.

**Comment by amarendrayadav** [comment]
Just upgraded to intellij 2020, "@Slf4j does not exist" in test package of a spring-boot project. I am using gradle as build tool. It works fine in java package but in test package the above error appears. 
Annotation processor should not be a problem as its working fine in java package. Fails only for test package
Invalidated cache and restarted once, same issue appears.

When I run the test case from cmd line using gradle, it does not give any error. But when run using run configuration from intellij - it shows @Slf4j does not exist

**Comment by dev2013slk** [comment]
> Hi, I am using intellij 15 with @slf4j and for me everything works fine. In my case help me **File > Invalidate Caches / Restart > Invalidate and Restart**

Perfect this works for me

**Comment by domainy** [comment]
Facing again added details here - https://github.com/projectlombok/lombok/issues/1855#issuecomment-1925343215
