### ISSUE TITLE
does not work on IntelliJ IDEA 2017.1.2 community

### ISSUE THREAD

**Issue by Pro100AlexHell** [mplushnikov/lombok-intellij-plugin#386]
IntelliJ IDEA 2017.1.2 community 
compiler is default javac.
JDK 1.8
Kotlin java project

plugin 0.14.16

1) plugin is installed http://prntscr.com/f7294w
(I have tried from remote, from disk)

2) Annotation processor is enabled
http://prntscr.com/f729gh
(when disable - plugin show error about 'Annotation processor' )

3)  restart many times, rebuild project many times, result is --

Error:(15, 2) java: cannot find symbol
  symbol: class EqualsAndHashCode
http://prntscr.com/f727xd
(other annotations doesn't work too)

** if I try install direct jar https://projectlombok.org/ then execure jar, then installer say like 'no IDEs compatible with lombok' - both immediate after run, and after manual select path to idea

-----

what is intellij-patcher-agent?
may be I need to add it somewhere?
if I download zip from releases
lombok-plugin-0.14.16\lombok-plugin\lib
it contains
lombok-plugin-0.14.16.jar
intellij-patcher-agent-0.14.16.jar

------

p.s. also I have re-read plugin manual
"Lombok project dependency
Make sure you have Lombok dependency added to your project. This plugin does not automatically add it for you."

I don't know how to add dependency, I don't use maven,gradle,etc.
may be I need to place some jar to classpath?
I have tried lombok.jar from official site but is's not work.
