### ISSUE TITLE
Support IntelliJ 2020.3

### ISSUE THREAD

**Issue by ewirch** [mplushnikov/lombok-intellij-plugin#940]
IntelliJ 2020.3 EAP just released. 

> Plugin 'Lombok' (version '0.31-2020.2') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.3645.34

**Comment by AlimkhanM** [comment]
Same problem, roll back to IntelliJ 2020.2.2 not working too :-1:

**Comment by shiyouxu** [comment]
how to build plugin?

**Comment by krzysztof-osiecki** [comment]
"Mateu MDD" is somewhat old fork of this plugin that seems to be working for now.

**Comment by rcunn87** [comment]
What is going on with this plugin, I used to run EAP's and the plugin would just work, but in the last 6-12 months worth of EAPs/Releases seems like the plugin is broken for a few days before it gets fixed.

**Comment by rcunn87** [comment]
Can the untilBuild field just be configured to not be populated? I tried this locally and installed in the EAP and everything seems to be fine.

**Comment by ztomic** [comment]
I have also tried locally build and install without 'untilBuild' on EAP and it is working fine.

https://jetbrains.org/intellij/sdk/docs/tutorials/build_system/gradle_guide.html#patching-the-plugin-configuration-file

Changed only in `build.gradle`:

```gradle
patchPluginXml {
  version artifactVersion

  pluginDescription(file(descriptionFile).text)
  changeNotes(file(changesFile).text)

  untilBuild(null)
}
```

**Comment by seenukarthi** [comment]
> Can the untilBuild field just be configured to not be populated? I tried this locally and installed in the EAP and everything seems to be fine.

This may work but if there is an issue like #829 then IntelliJ won't warn the user and after upgrade the plugin may not work properly.

**Comment by erodewald** [comment]
> > Can the untilBuild field just be configured to not be populated? I tried this locally and installed in the EAP and everything seems to be fine.
> 
> This may work but if there is an issue like #829 then IntelliJ won't warn the user and after upgrade the plugin may not work properly.

That's very true, but personally, I'd rather risk a chance that it may not work properly than a _guarantee_ that it won't work. Many people are dead in the water while we wait for an upgrade. I'll be building from sources as a workaround.

**Comment by rcunn87** [comment]
Right now the plugin just gets disabled and doesn't work at all.

**Comment by rcunn87** [comment]
I went ahead and opened a PR

**Comment by mplushnikov** [comment]
Just release 0.32 build, included one for IntelliJ 2020.3 EAP

**Comment by amiram** [comment]
The new EAP from today also breaks Lombok.In the IDE everything looks fine but build fails.
Message is:
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy27
  Lombok supports: sun/apple javac 1.6, ECJ

**Comment by mplushnikov** [comment]
@amiram Please make an issue in lombok project here:  https://github.com/rzwitserloot/lombok/issues
This can be fixed only in lombok self.

**Comment by brianvallred** [comment]
Did somebody log a bug? Is it being worked on?
I updated IntelliJ IDEA to version 2020.3 yesterday when prompted by IntelliJ, and it warned me that the Lombok plug-in was not compatible. I assumed there would be an updated plug-in available, but there is not. And I am not able to build my project.

**Comment by rcunn87** [comment]
Try uninstalling and reinstalling the plugin. Sometimes that helps fix this problem for me.

**Comment by seenukarthi** [comment]
> Did somebody log a bug? Is it being worked on?
> I updated IntelliJ IDEA to version 2020.3 yesterday when prompted by IntelliJ, and it warned me that the Lombok plug-in was not compatible. I assumed there would be an updated plug-in available, but there is not. And I am not able to build my project.

Starting from 2020.3 Lombok plugin is bundled with IntelliJ IDEA so uninstall the plugin and update IDEA. Lombok will work out of the box.

Tested in macOs Big Sur.

**Comment by sfitts** [comment]
@seenukarthi Is this only true for Ultimate or does it apply to the community edition as well?  In my case when I updated to 2020.3 (community), it set the plug-in version to 0.32 (had been 0.33).  When I did as you suggested and removed the plug-in entirely then my build broke (nothing with `val` or any of the annotations was recognized).

This is Windows and my project is Groovy/Java based on Gradle.

**Comment by seenukarthi** [comment]
> @seenukarthi Is this only true for Ultimate or does it apply to the community edition as well? In my case when I updated to 2020.3 (community), it set the plug-in version to 0.32 (had been 0.33). When I did as you suggested and removed the plug-in entirely then my build broke (nothing with `val` or any of the annotations was recognized).
> 
> This is Windows and my project is Groovy/Java based on Gradle.

Yes, you are correct. After fresh install of community version, I can see the plugin version is 0.32-EAP 

![image](https://user-images.githubusercontent.com/1208295/101312097-58100380-386c-11eb-90dc-ec658fff7c06.png)

In the plugin site It's 0.33-2020.2
 
![image](https://user-images.githubusercontent.com/1208295/101312170-855cb180-386c-11eb-9edb-3c5554cb7209.png)

I'm not sure this is a plugin issue or platform issue.

**Comment by sfitts** [comment]
Using 2020.3 and the 0.32 plug-in I am getting:

```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy32
  Lombok supports: sun/apple javac 1.6, ECJ
```

Above it says that this is a Lombok issue -- was one ever filed?

**Comment by sfitts** [comment]
OK, that was with Lombok 1.18.4.  If I updated to 1.18.16 I get:

```
java: Compilation failed: internal java compiler error
```

And essentially nothing builds.

**Comment by sfitts** [comment]
Logged https://github.com/rzwitserloot/lombok/issues/2670 based on the assertion above that this must be fixed in the core Lombok.
