### ISSUE TITLE
Lombok not working with IntelliJ IDEA 2020.3 EAP (Ultimate Edition).

### ISSUE THREAD

**Issue by UbaidurRehman1** [mplushnikov/lombok-intellij-plugin#950]
### Short description
Lombok 0.32-EAP is not working with IntelliJ IDEA 2020.3 EAP (Ultimate Edition). It shows first a warning
```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy25
  Lombok supports: OpenJDK javac, ECJ
```
and then error 
```
java: cannot find symbol
  symbol:   variable log
  location: class com.ubaid.ms.gatewayserver.logging.ZuulLoggingFilter
```
in build output. 

The code in ZuulLoggingFilter is:
*See the second line in run method*
```
@Component
@Slf4j
public class ZuulLoggingFilter extends ZuulFilter {

    /**
     * true for filter
     */
    @Override
    public boolean shouldFilter() {
        return true;
    }


    /**
     * actual method
     */
    @Override
    public Object run() {
        HttpServletRequest request = RequestContext.getCurrentContext().getRequest();
        log.info("request ---> {} request uri ---> {}", request, request.getRequestURI());
        return null;
    }
```

### Expected behavior
Java should recognize variable log. 

### Version information

 * **IDEA Version:**
```
IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4203.26, built on September 30, 2020
IntelliJ IDEA EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1098.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Non-Bundled Plugins: Lombook Plugin
Current Desktop: Pantheon
```
 * **JDK Version:**
 ```
java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```
 * **OS Type & Version:** 
```
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```
 * **Lombok Plugin Version:** _0.32-EAP_
 * **Lombok Dependency Version:** _1.18.12_

### Steps to reproduce
Please follow the following steps to reproduce the issue.
Note: Please follow the same version of IntelliJ Idea
 1. Open IntelliJ Idea 2020.3 EAP
 2. Click Get From VCS and Clone this https://github.com/UbaidurRehman1/Cloud-Native-App-Spring-Boot 
 3. After IntelliJ Resolving all dependencies, Click on Build button you will see the same errors. 

### Sample project
 - https://github.com/UbaidurRehman1/Cloud-Native-App-Spring-Boot 
 - I guess there is no need of .idea folder cause I just reproduced the errors with fresh clone. 

### Additional information
- Whenever I update my IntelliJ Idea to new versions (Like EAP or RC) it always happens.  

### Stacktrace
- No Stacktrace

**Comment by mplushnikov** [comment]
This is issue of lombok project. Please look here: https://github.com/rzwitserloot/lombok/issues/2592
Unfortunately this can be fixed only in lombok self.
