### ISSUE TITLE
fails to work in Intellij 13.0.2

### ISSUE THREAD

**Issue by torstenwerner** [mplushnikov/lombok-intellij-plugin#24]
Hi,

I am getting the following stacktrace with most current Intellij and lombok plugin:

java: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/code/TypeTags
    at lombok.javac.Javac.<clinit>(Javac.java:76)
    at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:294)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:339)
    at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
    at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:167)
    at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:152)
    at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
    at lombok.javac.apt.Processor.init(Processor.java:90)
    at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:89)
    at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:143)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)

**Comment by KolyaIvankov** [comment]
It's 2017, I have Lombok 1.16.16 on IntelliJ 2017.5.2, and having the same issue while trying to make runtime compilation.

**Comment by krimsonkart** [comment]
I am also having the same problem. Please help.

**Comment by krimsonkart** [comment]
For idea 2017, here is what i did
Go to your module settings. In the dependencies section, you have lombok-1.6.16 and then there is also a mvn dependency on lombok. Delete the lombok dependency and keep the mvn dependency. This fixed it for me. Let me know if this works for you also.
