### ISSUE TITLE
Support val

### ISSUE THREAD

**Issue by astubbs** [mplushnikov/lombok-intellij-plugin#9]
http://projectlombok.org/features/val.html

**Comment by samrg472** [comment]
+1

**Comment by hamen** [comment]
+1

**Comment by aria42** [comment]
+1

**Comment by Lekanich** [comment]
@akozlova Where are you added this feature ( com.intellij.psi.augment.PsiAugmentProvider#inferType ), it 's some branch in commons repo, or not?

**Comment by akozlova** [comment]
it's in master, corresponding EAP would be available shortly

**Comment by bsideup** [comment]
14.1 EAP is out. Let's rock!

**Comment by hamen** [comment]
Nice!
Right now I can use:
```java
        val lombokAllTheThings = "Lombok val test";
        Log.d("LOMBOK", lombokAllTheThings);
```
It builds and runs properly. I still get IntelliJ complaining about incompatible types: lombok.val vs String.
Looking forward to have it nice and clean :+1:

**Comment by samrg472** [comment]
@hamen You can build the latest plugin and have it nice and clean :smile: There are some issues however, such as if you try assigning a val it doesn't show an error saying it is final.

**Comment by hamen** [comment]
@samrg472 Thank you! I'll give it a try then :)

**Comment by Mast3rPlan** [comment]
:+1:

**Comment by johniak** [comment]
:+1:

**Comment by mplushnikov** [comment]
Version 0.9.0 of plugin is available now. It contains some work for this issue, feel free to test and comment it.

**Comment by mmoayyed** [comment]
GREAT! thanks. I'll start with lombok this weekend to possibly integrate it with CAS:
https://github.com/Jasig/cas/issues/475

**Comment by mogren** [comment]
:+1:

**Comment by fedotxxl** [comment]
So val correctly works in IDEA 14.1 but doesn't work in IDEA 14. Am I right?

**Comment by mplushnikov** [comment]
Yes, support (extension point) for val is providing only by IntelliJ 14.1 and later.

**Comment by fedotxxl** [comment]
gr8. Thank you

**Comment by mplushnikov** [comment]
Basic support available with plugin version 0.9.2 and IntelliJ 14.1
